/**
 * Write catalog-seed.json and lib/generated/catalog-data.ts
 */

import { writeFileSync, mkdirSync, existsSync } from "fs";
import { dirname, resolve } from "path";
import type { MappedCatalog } from "./map-products";

export function writeCatalogOutputs(
  mapped: MappedCatalog,
  opts?: { root?: string }
): { seedPath: string; generatedPath: string } {
  const root = opts?.root ?? process.cwd();
  const seedPath = resolve(root, "scripts", "output", "catalog-seed.json");
  const generatedPath = resolve(root, "lib", "generated", "catalog-data.ts");

  for (const p of [seedPath, generatedPath]) {
    const dir = dirname(p);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  }

  const payload = {
    generatedAt: new Date().toISOString(),
    currency: "COP",
    region: "co",
    wholesaleDiscountDefault: 0.2,
    customerGroup: "emprendedores",
    salesChannels: ["retail", "wholesale"],
    collections: [
      { handle: "perfumeria", title: "Perfumería" },
      { handle: "insumos", title: "Insumos" },
      { handle: "hogar", title: "Hogar y cuidado" },
      { handle: "accesorios", title: "Accesorios" },
    ],
    products: mapped.seedProducts,
    count: mapped.seedProducts.length,
    summary: mapped.summary,
  };

  writeFileSync(seedPath, JSON.stringify(payload, null, 2), "utf8");

  const ts = `/**
 * AUTO-GENERATED by scripts/catalog — do not edit by hand.
 * Re-run: npm run catalog:import -- --fragancias <path> --perfumas <path>
 */
import type { Bottle, Fragrance, LooseComponent } from "../types";
import type { CatalogProduct } from "../catalog-types";

export const GENERATED_AT = ${JSON.stringify(payload.generatedAt)};

export const OLFACTIVE_GROUPS = ${JSON.stringify(mapped.olfactiveGroups, null, 2)} as const;

export const FRAGRANCES: Fragrance[] = ${JSON.stringify(mapped.fragrances, null, 2)} as Fragrance[];

export const BOTTLES: Bottle[] = ${JSON.stringify(mapped.bottles, null, 2)} as Bottle[];

export const ALCOHOL_OPTIONS: LooseComponent[] = ${JSON.stringify(mapped.alcoholOptions, null, 2)} as LooseComponent[];

export const DEFAULT_BUILD_ALCOHOL = ALCOHOL_OPTIONS[0];

export const GIFT_WRAP_FEE = ${mapped.giftWrapFee};

export const PHEROMONES: CatalogProduct[] = ${JSON.stringify(mapped.pheromones, null, 2)} as CatalogProduct[];

export const CATALOG_PRODUCTS: CatalogProduct[] = ${JSON.stringify(mapped.catalogProducts, null, 2)} as CatalogProduct[];

export const HOUSES: string[] = Array.from(new Set(FRAGRANCES.map((f) => f.house))).sort();

export const CATALOG_SUMMARY = ${JSON.stringify(mapped.summary, null, 2)} as const;
`;

  writeFileSync(generatedPath, ts, "utf8");

  return { seedPath, generatedPath };
}
